/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pw.misa.kk6.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import pw.misa.kk6.controllers.CollectionController;

/**
 *
 * @author ASUS
 */
public class BuatKoleksi extends javax.swing.JFrame {

    CollectionController cc;
    /**
     * Creates new form BuatKoleksi
     * @param controller
     */
    public BuatKoleksi(CollectionController controller) {
        initComponents();
        this.cc = controller;
    }

    public JLabel getBuatKoleksi() {
        return BuatKoleksi;
    }

    public JTextField getIsiJudul() {
        return IsiJudul;
    }

    public JTextField getIsiKodeBaru() {
        return IsiKodeBaru;
    }

    public JTextField getIsiPassword() {
        return IsiPassword;
    }

    public JLabel getJudul() {
        return Judul;
    }

    public JLabel getKodeBaru() {
        return KodeBaru;
    }

    public JLabel getMasukanDok() {
        return MasukanDok;
    }

    public JLabel getPassword() {
        return Password;
    }

    public JButton getTombolBuat() {
        return TombolBuat;
    }

    public JButton getTombolkembali() {
        return Tombolkembali;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JTable getTabelDokumenTerbaru1() {
        return TabelDokumenTerbaru1;
    }

    public JTextArea getIsiKodeDok() {
        return IsiKodeDok;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tombolkembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDokumenTerbaru1 = new javax.swing.JTable();
        BuatKoleksi = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        IsiJudul = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        IsiPassword = new javax.swing.JTextField();
        KodeBaru = new javax.swing.JLabel();
        TombolBuat = new javax.swing.JButton();
        IsiKodeBaru = new javax.swing.JTextField();
        MasukanDok = new javax.swing.JLabel();
        IsiKodeDok = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        Tombolkembali.setText("Kembali");
        Tombolkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolkembaliActionPerformed(evt);
            }
        });

        TabelDokumenTerbaru1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Judul", "Jumlah Akses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDokumenTerbaru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDokumenTerbaru1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelDokumenTerbaru1);

        BuatKoleksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BuatKoleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuatKoleksi.setText("Buat Koleksi");

        Judul.setText("Judul :");

        Password.setText("Password :");

        KodeBaru.setText("Kode baru :");

        TombolBuat.setText("Buat");
        TombolBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBuatActionPerformed(evt);
            }
        });

        IsiKodeBaru.setText("Tidak Perlu Diisi!!");

        MasukanDok.setText("Masukan Dokumen :");

        IsiKodeDok.setColumns(20);
        IsiKodeDok.setLineWrap(true);
        IsiKodeDok.setRows(5);
        IsiKodeDok.setWrapStyleWord(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Judul)
                                            .addGap(87, 87, 87)
                                            .addComponent(IsiJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(MasukanDok))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(KodeBaru)
                                                .addGap(59, 59, 59)
                                                .addComponent(IsiKodeBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Password)
                                                .addGap(65, 65, 65)
                                                .addComponent(IsiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TombolBuat)
                                    .addGap(219, 219, 219)))
                            .addComponent(IsiKodeDok, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(BuatKoleksi))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuatKoleksi)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(Judul))
                                .addComponent(IsiJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MasukanDok))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Password)
                                .addComponent(IsiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(TombolBuat)
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KodeBaru)
                                .addComponent(IsiKodeBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1))
                    .addComponent(IsiKodeDok, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(Tombolkembali)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBuatActionPerformed
        cc.insertCollec();
        cc.reset();
    }//GEN-LAST:event_TombolBuatActionPerformed

    private void TombolkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolkembaliActionPerformed
        cc.kembali();
    }//GEN-LAST:event_TombolkembaliActionPerformed

    private void TabelDokumenTerbaru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDokumenTerbaru1MouseClicked
        cc.addDocLatesDocument(TabelDokumenTerbaru1.getSelectedRow());
    }//GEN-LAST:event_TabelDokumenTerbaru1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuatKoleksi;
    private javax.swing.JTextField IsiJudul;
    private javax.swing.JTextField IsiKodeBaru;
    private javax.swing.JTextArea IsiKodeDok;
    private javax.swing.JTextField IsiPassword;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel KodeBaru;
    private javax.swing.JLabel MasukanDok;
    private javax.swing.JLabel Password;
    private javax.swing.JTable TabelDokumenTerbaru1;
    private javax.swing.JButton TombolBuat;
    private javax.swing.JButton Tombolkembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
