/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pw.misa.kk6.views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import pw.misa.kk6.controllers.CollectionController;

/**
 *
 * @author ASUS
 */
public class BuatKoleksi extends javax.swing.JFrame {

    CollectionController cc;
    /**
     * Creates new form BuatKoleksi
     * @param controller
     */
    public BuatKoleksi(CollectionController controller) {
        initComponents();
        this.cc = controller;
    }

    public JLabel getBuatKoleksi() {
        return BuatKoleksi;
    }

    public JTextField getIsiJudul() {
        return IsiJudul;
    }

    public JTextField getIsiKodeBaru() {
        return IsiKodeBaru;
    }

    public JTextField getIsiKodeDok() {
        return IsiKodeDok;
    }

    public JTextField getIsiPassword() {
        return IsiPassword;
    }

    public JLabel getJudul() {
        return Judul;
    }

    public JLabel getKodeBaru() {
        return KodeBaru;
    }

    public JLabel getMasukanDok() {
        return MasukanDok;
    }

    public JLabel getPassword() {
        return Password;
    }

    public JButton getTombolBuat() {
        return TombolBuat;
    }

    public JButton getTombolkembali() {
        return Tombolkembali;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        BuatKoleksi = new javax.swing.JLabel();
        IsiJudul = new javax.swing.JTextField();
        IsiKodeDok = new javax.swing.JTextField();
        MasukanDok = new javax.swing.JLabel();
        IsiPassword = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        TombolBuat = new javax.swing.JButton();
        IsiKodeBaru = new javax.swing.JTextField();
        KodeBaru = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Tombolkembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDokumenTerbaru1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setText("Judul :");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        BuatKoleksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BuatKoleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuatKoleksi.setText("Buat Koleksi");
        getContentPane().add(BuatKoleksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));
        getContentPane().add(IsiJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 245, -1));

        IsiKodeDok.setActionCommand("<Not Set>");
        IsiKodeDok.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(IsiKodeDok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 244, -1));

        MasukanDok.setText("Masukan Dokumen :");
        getContentPane().add(MasukanDok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));
        getContentPane().add(IsiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 242, -1));

        Password.setText("Password :");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        TombolBuat.setText("Buat");
        TombolBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBuatActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));
        getContentPane().add(IsiKodeBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 242, -1));

        KodeBaru.setText("Kode baru :");
        getContentPane().add(KodeBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        Tombolkembali.setText("Kembali");
        Tombolkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolkembaliActionPerformed(evt);
            }
        });

        TabelDokumenTerbaru1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Judul", "Jumlah Akses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDokumenTerbaru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDokumenTerbaru1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelDokumenTerbaru1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(Tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(Tombolkembali)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBuatActionPerformed
        cc.insertCollec();
    }//GEN-LAST:event_TombolBuatActionPerformed

    private void TombolkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolkembaliActionPerformed
        cc.kembali();
    }//GEN-LAST:event_TombolkembaliActionPerformed

    private void TabelDokumenTerbaru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDokumenTerbaru1MouseClicked
        //dc.isiField(TabelDokumenTerbaru.getSelectedRow());
    }//GEN-LAST:event_TabelDokumenTerbaru1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatKoleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuatKoleksi;
    private javax.swing.JTextField IsiJudul;
    private javax.swing.JTextField IsiKodeBaru;
    private javax.swing.JTextField IsiKodeDok;
    private javax.swing.JTextField IsiPassword;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel KodeBaru;
    private javax.swing.JLabel MasukanDok;
    private javax.swing.JLabel Password;
    private javax.swing.JTable TabelDokumenTerbaru1;
    private javax.swing.JButton TombolBuat;
    private javax.swing.JButton Tombolkembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
