/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pw.misa.kk6.views;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import pw.misa.kk6.controllers.DocumentController;

/**
 *
 * @author ASUS
 */
public class BuatDokumen extends javax.swing.JFrame {

    DocumentController dc;
    /**
     * Creates new form CreateCollect
     * @param controller
     */
    public BuatDokumen(DocumentController controller) {
        initComponents();
        this.dc = controller;
    }

    public DocumentController getDc() {
        return dc;
    }

    public JLabel getBuatDokumen() {
        return BuatDokumen;
    }

    public JTextField getIsiJudul() {
        return IsiJudul;
    }

    public JTextField getIsiKodeBaru() {
        return IsiKodeBaru;
    }

    public JTextField getIsiPassword() {
        return IsiPassword;
    }

    public JTextField getIsiTeks() {
        return IsiTeks;
    }

    public JLabel getJudul() {
        return Judul;
    }

    public JLabel getKodeBaru() {
        return KodeBaru;
    }

    public JLabel getPassword() {
        return Password;
    }

    public JRadioButton getPublic() {
        return Public;
    }

    public JLabel getTeks() {
        return Teks;
    }

    public JLabel getTipe() {
        return Tipe;
    }

    public JButton getTombolBuat() {
        return TombolBuat;
    }

    public JButton getTombolkembali() {
        return Tombolkembali;
    }

    public JRadioButton getUnlisted() {
        return Unlisted;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Teks = new javax.swing.JLabel();
        IsiTeks = new javax.swing.JTextField();
        IsiJudul = new javax.swing.JTextField();
        Judul = new javax.swing.JLabel();
        BuatDokumen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Tombolkembali = new javax.swing.JButton();
        Unlisted = new javax.swing.JRadioButton();
        Public = new javax.swing.JRadioButton();
        IsiPassword = new javax.swing.JTextField();
        TombolBuat = new javax.swing.JButton();
        IsiKodeBaru = new javax.swing.JTextField();
        KodeBaru = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Tipe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Teks.setText("Teks :");
        getContentPane().add(Teks, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 83, -1, -1));
        getContentPane().add(IsiTeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 83, 260, 121));
        getContentPane().add(IsiJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 49, 260, -1));

        Judul.setText("Judul :");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, -1, -1));

        BuatDokumen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BuatDokumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuatDokumen.setText("Buat Dokumen");
        getContentPane().add(BuatDokumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 6, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tombolkembali.setText("Kembali");
        Tombolkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Tombolkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 90, -1));

        buttonGroup1.add(Unlisted);
        Unlisted.setText("Unlisted");
        jPanel1.add(Unlisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        buttonGroup1.add(Public);
        Public.setText("Public");
        jPanel1.add(Public, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
        jPanel1.add(IsiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 269, -1));

        TombolBuat.setText("Buat");
        TombolBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBuatActionPerformed(evt);
            }
        });
        jPanel1.add(TombolBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));
        jPanel1.add(IsiKodeBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 269, -1));

        KodeBaru.setText("Kode baru :");
        jPanel1.add(KodeBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        Password.setText("Password :");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        Tipe.setText("Tipe");
        jPanel1.add(Tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBuatActionPerformed
        dc.insertDocument();
        dc.isiLatesDocument();
    }//GEN-LAST:event_TombolBuatActionPerformed

    private void TombolkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolkembaliActionPerformed
        dc.kembali();
    }//GEN-LAST:event_TombolkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatDokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatDokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatDokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatDokumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuatDokumen;
    private javax.swing.JTextField IsiJudul;
    private javax.swing.JTextField IsiKodeBaru;
    private javax.swing.JTextField IsiPassword;
    private javax.swing.JTextField IsiTeks;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel KodeBaru;
    private javax.swing.JLabel Password;
    private javax.swing.JRadioButton Public;
    private javax.swing.JLabel Teks;
    private javax.swing.JLabel Tipe;
    private javax.swing.JButton TombolBuat;
    private javax.swing.JButton Tombolkembali;
    private javax.swing.JRadioButton Unlisted;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
