/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pw.misa.kk6.views;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import pw.misa.kk6.controllers.CollectionController;
import pw.misa.kk6.controllers.DocumentController;
/**
 *
 * @author Isabu
 */
public class MainMenu extends javax.swing.JFrame {

    DocumentController dc;
    CollectionController cc;
    /**
     * Creates new form MainView
     */
    public MainMenu() {
        initComponents();
        dc = new DocumentController(this);
        cc = new CollectionController(this);
        dc.isiLatesDocument();
    }

    public DocumentController getDc() {
        return dc;
    }

    public CollectionController getCc() {
        return cc;
    }

    public JLabel getAkses() {
        return Akses;
    }

    public JLabel getBuat() {
        return Buat;
    }

    public JLabel getDokumenTerbaru() {
        return DokumenTerbaru;
    }

    public JTextField getIsiKode() {
        return IsiKode;
    }

    public JPasswordField getIsiPasswordAkses() {
        return IsiPasswordAkses;
    }

    public JLabel getKode() {
        return Kode;
    }

    public JLabel getPasswordAkses() {
        return PasswordAkses;
    }

    public JRadioButton getRadioButton1() {
        return RadioButton1;
    }

    public JRadioButton getRadioButton2() {
        return RadioButton2;
    }

    public JTable getTabelDokumenTerbaru() {
        return TabelDokumenTerbaru;
    }

    public JLabel getTipeAkses() {
        return TipeAkses;
    }

    public JButton getTombolAkses1() {
        return TombolAkses1;
    }

    public JButton getTombolBuatDok() {
        return TombolBuatCollec;
    }

    public JButton getTombolBuatDok1() {
        return TombolBuatDok1;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDokumenTerbaru = new javax.swing.JTable();
        DokumenTerbaru = new javax.swing.JLabel();
        IsiKode = new javax.swing.JTextField();
        TombolBuatCollec = new javax.swing.JButton();
        IsiPasswordAkses = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        Kode = new javax.swing.JLabel();
        PasswordAkses = new javax.swing.JLabel();
        TipeAkses = new javax.swing.JLabel();
        Buat = new javax.swing.JLabel();
        Akses = new javax.swing.JLabel();
        TombolAkses1 = new javax.swing.JButton();
        TombolBuatDok1 = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelDokumenTerbaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Judul", "Jumlah Akses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDokumenTerbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDokumenTerbaruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDokumenTerbaru);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 807, 168));

        DokumenTerbaru.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DokumenTerbaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DokumenTerbaru.setText("Dokumen Terbaru");
        getContentPane().add(DokumenTerbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, 808, -1));
        getContentPane().add(IsiKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 315, 220, -1));

        TombolBuatCollec.setText("Buat Collection Baru");
        TombolBuatCollec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBuatCollecActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBuatCollec, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 220, -1));
        getContentPane().add(IsiPasswordAkses, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 349, 220, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 0, 1, 437));

        buttonGroup1.add(RadioButton1);
        RadioButton1.setText("Dokumen");
        getContentPane().add(RadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 282, -1, -1));

        buttonGroup1.add(RadioButton2);
        RadioButton2.setText("Koleksi");
        getContentPane().add(RadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 282, -1, -1));

        Kode.setText("Kode");
        getContentPane().add(Kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 318, -1, -1));

        PasswordAkses.setText("Password");
        getContentPane().add(PasswordAkses, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 349, -1, -1));

        TipeAkses.setText("Tipe");
        getContentPane().add(TipeAkses, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 284, -1, -1));

        Buat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Buat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Buat.setText("Buat");
        getContentPane().add(Buat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 308, 22));

        Akses.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Akses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Akses.setText("Akses");
        getContentPane().add(Akses, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 308, 22));

        TombolAkses1.setText("Akses");
        TombolAkses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolAkses1ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolAkses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 389, 220, -1));

        TombolBuatDok1.setText("Buat Dokumen Baru");
        TombolBuatDok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBuatDok1ActionPerformed(evt);
            }
        });
        getContentPane().add(TombolBuatDok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 220, -1));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelDokumenTerbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDokumenTerbaruMouseClicked
        dc.isiField(TabelDokumenTerbaru.getSelectedRow());
    }//GEN-LAST:event_TabelDokumenTerbaruMouseClicked

    private void TombolBuatCollecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBuatCollecActionPerformed
        cc.buatCollec();
    }//GEN-LAST:event_TombolBuatCollecActionPerformed

    private void TombolAkses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolAkses1ActionPerformed
        if(RadioButton1.isSelected()){
            dc.aksesDoc();
        }else if(RadioButton2.isSelected()){
            cc.aksesCollec();
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih tipe terlebih dahulu.");
        }
    }//GEN-LAST:event_TombolAkses1ActionPerformed

    private void TombolBuatDok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBuatDok1ActionPerformed
        dc.buatDoc();
    }//GEN-LAST:event_TombolBuatDok1ActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        dc.isiLatesDocument();
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akses;
    private javax.swing.JLabel Buat;
    private javax.swing.JLabel DokumenTerbaru;
    private javax.swing.JTextField IsiKode;
    private javax.swing.JPasswordField IsiPasswordAkses;
    private javax.swing.JLabel Kode;
    private javax.swing.JLabel PasswordAkses;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable TabelDokumenTerbaru;
    private javax.swing.JLabel TipeAkses;
    private javax.swing.JButton TombolAkses1;
    private javax.swing.JButton TombolBuatCollec;
    private javax.swing.JButton TombolBuatDok1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
